routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/*
|--------------------------------------------------------------------------
| Hosts
|--------------------------------------------------------------------------
|
*/
Route::resource('hosts', 'HostController');
Route::post('hosts_miscellaneous/index_search', 'HostController@search')->name('hosts_miscellaneous.index_search');
/*
|--------------------------------------------------------------------------
| Appointments
|--------------------------------------------------------------------------
|
*/
Route::resource('appointments', 'AppointmentController');
Route::post('appointments_miscellaneous/index_search', 'AppointmentController@search')->name('appointments_miscellaneous.index_search');

/*
|--------------------------------------------------------------------------
| Admin Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get('admin_dashboard/home', 'Dashboard\AdminDashboardController@home')
->name('admin_dashboard.home');
/*
|--------------------------------------------------------------------------
| Host Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get('host_dashboard/home', 'Dashboard\HostDashboardController@home')
->name('host_dashboard.home');
Route::get('host_dashboard/join_appointment', 'Dashboard\HostDashboardController@joinAppointment')
    ->name('host_dashboard.join_appointment');
Route::post('host_dashboard/join_appointment_get_signature', 'Dashboard\HostDashboardController@joinAppointmentGetSignature')
    ->name('host_dashboard.join_appointment_get_signature');
/*
|--------------------------------------------------------------------------
| Attendee Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get('attendee_dashboard/home', 'Dashboard\AttendeeDashboardController@home')
    ->name('attendee_dashboard.home');
Route::get('attendee_dashboard/reserve_appointment', 'Dashboard\AttendeeDashboardController@reserveAppointment')
    ->name('attendee_dashboard.reserve_appointment');
Route::get('attendee_dashboard/join_appointment', 'Dashboard\AttendeeDashboardController@joinAppointment')
    ->name('attendee_dashboard.join_appointment');
Route::post('attendee_dashboard/join_appointment_get_signature', 'Dashboard\AttendeeDashboardController@joinAppointmentGetSignature')
    ->name('attendee_dashboard.join_appointment_get_signature');

app/User.php
<?php

namespace App;

use App\Role;
use App\Services\Models\User\Type\UserType;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Builder;

class User extends Authenticatable
{
    use Notifiable;

    /*
    |--------------------------------------------------------------------------
    | Attributes
    |--------------------------------------------------------------------------
    */

    public $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type', 'first_name', 'last_name', 'email', 'password', 'notes', 'creator_id', 'last_updater_id',
        'master_role_id', 'admin_who_generate_hosts_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = [
        'name',
        'user_show_link',
        'host_show_link',
    ];

    /*
    |--------------------------------------------------------------------------
    | Getters and Setters
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Accessors
    |--------------------------------------------------------------------------
    */

    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    public function getUserShowLinkAttribute(): string
    {
        return '<a href="' . action('UserController@show', ['user' => $this->id]) . '" target="_blank">' . $this->name . '</a>';
    }

    public function getUserRolesNamesIdsAttribute(): array
    {
        $roles = $this->roles;
        if ($roles->isEmpty()) {
            return [];
        }
        return $roles->pluck('name', 'id')->toArray();
    }

    public function getHostShowLinkAttribute()
    {
        return '<a href="' . action('HostController@show', ['host' => $this->id]) . '" target="_blank">' . $this->name . '</a>';
    }

    public function getTypesAttribute()
    {
        return UserType::toArray();
    }

    public function getTypeAttribute($type)
    {
        $routeName = request()->route()
            ->getName();

        if (
            $routeName == 'users.show' ||
            $routeName == 'users.index' ||
            $routeName == 'users_miscellaneous.index_search'
        ) {
            return UserType::selectedValue($type);
        }
        return $type;
    }

    /*
    |--------------------------------------------------------------------------
    | Mutators
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    /**
     * Getting the creator user who create this user.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Recursive
     *
     * @return BelongsTo
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id', 'id');
    }

    /**
     * Getting the users that are created by creator user.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Recursive
     *
     * @return HasMany
     */
    public function createdUsers(): HasMany
    {
        return $this->hasMany(User::class, 'creator_id', 'id');
    }

    /**
     * Getting the last updater user who update this user.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Recursive
     *
     * @return BelongsTo
     */
    public function lastUpdater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the users that are updated by the last updater user.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Recursive
     *
     * @return HasMany
     */
    public function updatedUsers(): HasMany
    {
        return $this->hasMany(User::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the permissions that are created by this user.
     *
     * @return HasMany
     */
    public function createdPermissions(): HasMany
    {
        return $this->hasMany(Permission::class, 'creator_id', 'id');
    }

    /**
     * Getting the roles that are created by this user.
     *
     * @return HasMany
     */
    public function createdRoles(): HasMany
    {
        return $this->hasMany(Role::class, 'creator_id', 'id');
    }

    /**
     * Getting the profiles that are created by this user.
     *
     * @return HasMany
     */
    public function createdProfiles(): HasMany
    {
        return $this->hasMany(Profile::class, 'creator_id', 'id');
    }

    /**
     * Getting the profiles that are created by this user.
     *
     * @return HasMany
     */
    public function createdAppointments(): HasMany
    {
        return $this->hasMany(Appointment::class, 'creator_id', 'id');
    }

    //*************************** */

    /**
     * Getting the permissions that are created by this user.
     *
     * @return HasMany
     */
    public function updatedPermissions(): HasMany
    {
        return $this->hasMany(Permission::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the roles that are updated by this user.
     *
     * @return HasMany
     */
    public function updatedRoles(): HasMany
    {
        return $this->hasMany(Role::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the profiles that are updated by this user.
     *
     * @return HasMany
     */
    public function updatedProfiles(): HasMany
    {
        return $this->hasMany(Profile::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the profiles that are updated by this user.
     *
     * @return HasMany
     */
    public function updatedAppointments(): HasMany
    {
        return $this->hasMany(Appointment::class, 'last_updater_id', 'id');
    }



    //-------------------------


    public function masterRole(): BelongsTo
    {
        return $this->belongsTo(Role::class, 'master_role_id', 'id');
    }

    /**
     * Getting the roles that are associated with this user.
     *
     * @return BelongsToMany
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }

    /**
     * Getting user profile
     *
     * @return HasOne
     */
    public function profile(): HasOne
    {
        return $this->hasOne(Profile::class, 'user_id', 'id');
    }

    /**
     * Admin perspective
     * Getting hosts that are associated with this admin
     * relationship type: Recursive
     * @return HasMany
     */
    public function hostsGeneratedByAdmin(): HasMany
    {
        return $this->hasMany(User::class, 'admin_who_generate_hosts_id', 'id');
    }

    /**
     * Host perspective
     * Getting the admin that generate this host
     * relationship type: Recursive
     * @return BelongsTo
     */
    public function adminWhoGenerateHost(): BelongsTo
    {
        return $this->belongsTo(User::class, 'admin_who_generate_hosts_id', 'id');
    }

    /**
     * Getting the appointments that are assigned for this host.
     *
     * @return HasMany
     */
    public function hostAppointments(): HasMany
    {
        return $this->hasMany(Appointment::class, 'host_id', 'id');
    }

    /**
     * Getting the appointments reserved by this attendee.
     *
     * @return HasMany
     */
    public function attendeeAppointments(): HasMany
    {
        return $this->hasMany(Appointment::class, 'attendee_id', 'id');
    }

    /*
    |--------------------------------------------------------------------------
    | Miscellaneous
    |--------------------------------------------------------------------------
     */

    public function getPermissionsNamesAsArray(): array
    {
        $roles = $this->roles;
        $permissionsNamesAsArray = [];
        if ($roles->isNotEmpty()) {
            foreach ($roles as $role) {
                $permissions = $role->permissions;
                if ($permissions->isNotEmpty()) {
                    foreach ($permissions as $permission) {
                        $permissionsNamesAsArray[] = $permission->name;
                    }
                }
            }
        }
        return $permissionsNamesAsArray;
    }

    public function search(Builder $builder, $keyword)
    {
        $name = explode(' ', $keyword);
        $firstName = isset($name[0])?($name[0]):('');
        $lastName = (count($name) > 1)?($name[1]):('');

        if ($firstName && !$lastName) {
            $results = $builder->with('roles', 'creator')
                ->where('first_name', 'like', "%$firstName%")
                ->get();
            return $results;
        }

        if ($firstName && $lastName) {
            $results = $builder->with('roles', 'creator')
                ->where('first_name', 'like', "%$firstName%")
                ->Where('last_name', 'like', "%$lastName%")
                ->get();
            return $results;
        }
    }

    public function searchForHost(Builder $builder, $keyword)
    {
        $name = explode(' ', $keyword);
        $firstName = isset($name[0])?($name[0]):('');
        $lastName = (count($name) > 1)?($name[1]):('');

        $builder = $builder->where('type', UserType::HOST);

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Closure;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use App\Services\FileUploader\FileUploaderInterface;
use App\Services\IndexTenancy\IndexStrategyInterface;
use App\Services\LanguageLocator\LanguageLocatorTrait;
use App\Services\Models\User\CreateUserStrategy\CreateUserInterface;
use App\Services\Models\User\DeleteUserStrategy\DeleteUserInterface;
use App\Services\Models\User\UpdateUserStrategy\UpdateUserInterface;

class UserController extends Controller
{
    use LanguageLocatorTrait;
    /*
    |--------------------------------------------------------------------------
    | Attributes
    |--------------------------------------------------------------------------
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Constructors
    |--------------------------------------------------------------------------
    |
    */

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('users_rbac');
        $this->middleware('users_multi_tenancy')->only(['show', 'edit', 'update', 'destroy']);

        $this->middleware(function ($request, Closure $next) {
            session(['highlighSelectedNav' => 'userSystem']);
            return $next($request);
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Getters, Setters & Interface implementations
    |--------------------------------------------------------------------------
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Core
    |--------------------------------------------------------------------------
    |
    */

    public function index(IndexStrategyInterface $indexByMultiTenancy)
    {
        $authenticatedUser = request()->user();
        $builder = $indexByMultiTenancy
            ->index($authenticatedUser, $authenticatedUser, 'index_users_multi_tenancy');
        $users = $builder->paginate(20);
        return view('users.index', compact('users'));
    }

    public function create(User $user)
    {
        return view('users.create', compact('user'));
    }


    public function store(
        UserRequest $request,
        CreateUserInterface $createUser
    ) {
        $user = $createUser->create($request);
        flash()->success(__('user.user_added_successfully'));
        return redirect()->action('UserController@show', ['user' => $user->id]);
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit', compact('user'));
    }

    public function update(
        UserRequest $request,
        int $id,
        UpdateUserInterface $updateUser
    ) {
        $user = $updateUser->update($id, $request);
        flash()
            ->success(__('user.user_updated_successfully'))
            ->important();
        return redirect()->action('UserController@show', ['user' => $user->id]);
    }

    public function destroy(User $user, DeleteUserInterface $deleteUser, FileUploaderInterface $fileUploader)
    {
        $deleteUser->delete($user, $fileUploader);
        flash()
            ->success(__('user.user_deleted_successfully_segment_1') . __('user.user_deleted_successfully_segment_2'))
            ->important();
        return redirect('users');
    }

    /*
    |--------------------------------------------------------------------------
    | Miscellaneous
    |--------------------------------------------------------------------------
    */

    public function indexUsersNotVerifiedEmail()
    {
        $usersNotVerified = User::whereNull('email_verified_at')->paginate(25);
        return view('users.index_users_not_verified_email', compact('usersNotVerified'));
    }

    public function verifyUserEmail(User $user)
    {
        $user->update(['email_verified_at' => now()]);
        flash()->success('تم تفعيل اشتراك المستخدم: ' . $user->name)->important();
        return redirect()->action('UserController@indexUsersNotVerifiedEmail');
    }

    /*
    |--------------------------------------------------------------------------
    | Miscellaneous - Ajax
    |--------------------------------------------------------------------------
    */

    public function search(Request $request, IndexStrategyInterface $indexStrategy)
    {
        $authenticatedUser = request()->user();
        $builder = $indexStrategy
            ->index($authenticatedUser, $authenticatedUser, 'index_users_multi_tenancy');
        $results = $authenticatedUser->search($builder, $request->input('keyword'));
        return $results;
    }
}

resources/views/users/_form.blade.php
<div class="row">

	<div class="col-lg-12">

		@if (in_array('store_roles', $permissions) || in_array('update_roles', $permissions))
			<div class='form-group'>
				{!!Form::label('master_role_id', __('user.master_role_id'))!!}
				{!!Form::select('master_role_id', $user->user_roles_names_ids, null,['class'=>'form-control', 'placeholder'=>__('user.master_role_id_placeholder')]) !!}
			</div>
        @endif
        <div class='form-group'>
            <span style='color:#f47373'>*</span>
            {!!Form::label('type', __('user.type'))!!}
            {!!Form::select('type', $user->types, null,['class'=>'form-control', 'placeholder'=>__('user.type_placeholder')]) !!}
        </div>

		<div class="form-group">
			<span style="color:#f47373">*</span>
			{!!Form::label('first_name', __('user.first_name'))!!}
			{!!Form::text('first_name', null,['class'=>'form-control', 'placeholder'=>__('user.first_name_placeholder')]) !!}
        </div>

		<div class="form-group">
			<span style="color:#f47373">*</span>
			{!!Form::label('last_name', __('user.last_name'))!!}
			{!!Form::text('last_name', null,['class'=>'form-control', 'placeholder'=>__('user.last_name_placeholder')]) !!}
		</div>

		<div class="form-group">
			<span style="color:#f47373">*</span>
			{!!Form::label('email', __('user.email'))!!}
			{!!Form::email('email', null, ['class'=>'form-control', 'placeholder'=>__('user.email_placeholder')])!!}
		</div>

		<div class="form-group">
			<span style="color:#f47373">*</span>
			{!!Form::label('password', __('user.password'))!!}
			{!!Form::password('password', ['class'=>'form-control', 'placeholder'=>__('user.password_placeholder')])!!}
		</div>

		<div class="form-group">
			<span style="color:#f47373">*</span>
			{!!Form::label('password_confirmation', __('user.password_confirmation'))!!}
			{!!Form::password('password_confirmation', ['class'=>'form-control', 'placeholder'=>__('user.password_confirmation_placeholder')])!!}
		</div>


		<div class='form-group'>
			{!!Form::label('notes', __('user.notes'))!!}
			{!!Form::textarea('notes', null, ['class'=>'form-control', 'rows'=>'5', 'placeholder'=>__('user.notes_placeholder')])!!}
		</div>

		<div class="form-group">
			{!!Form::submit(__('user.save'), ['class'=>'btn btn-primary form-control'])!!}
		</div>
	</div>
</div>

resources/views/users/create.blade.php
@extends('layouts.app')
@section('title')
	{{__('user.add_user')}}
@endsection
@section('content')
	<div class="col-md-12">
		<div class="card card-info">
		<div class="card-heading">
			<h3 class="card-header text-center">{{__('user.add_user')}}</h3>
		</div>
			<div class="card-body ">
				@include('errors.list')
				{!! Form::open(['action' => ['UserController@store'], 'files'=>true, 'method'=>'POST'])!!}
					@include('users._form')
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title')
	Edit profile
@endsection
@section('content')
	<div class="col-md-12">
		<div class="card card-info">
		<div class="card-heading">
			<h3 class="card-header text-center">{{$user->name}}</h3>
		</div>
			<div class="card-body ">
				@include('errors.list')
				{!! Form::model($user, ['action' => ['UserController@update', 'user'=>$user->id], 'files'=>true, 'method'=>'put'])!!}
					@include('users._form')
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title')
	{{__('user.all_users')}}
@endsection
@section('content-name')
    {{__('user.all_users')}}
@endsection
@section('content')
		<div class="card">

				<div class="card-body">
					<div class="form-inline">
						<div class="input-group mb-2 mr-sm-2">
							<label class="m-2" for="searching-input">{{__('user.searching_on_user')}}: </label>
							<input type="text" class="form-control" id="searching-input" placeholder="{{__('user.searching_word')}}" autofocus>
						</div>

						<button id="searching-button" type="button" class="btn btn-primary mb-2">{{__('user.search')}}</button>
						<input id="searching-button-required" type="hidden" value="{{__('user.searching_button_required')}}">
						<input id="searching-button-searching" type="hidden" value="{{__('user.searching_button_searching')}}">
						<input id="searching-button-search" type="hidden" value="{{__('user.searching_button_search')}}">
					</div>
                    <hr>
                    <div class="table-responsive">
                        <table class="table table-hover" id="users">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Type</th>
                                    <th>Role</th>
                                    <th>created at</th>
                                    <th>Creator name</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $userKey => $user)
                                    <tr>
                                        <td>{{$userKey+1}}</td>
                                        <td>{{$user->id}}</td>
                                        <td>
                                            {!!$user->user_show_link!!}
                                        </td>

                                        <td>{{$user->email}}</td>
                                        <td>{{$user->type}}</td>
                                        <td>
                                            @if($user->roles->isNotEmpty())
                                                @foreach ($user->roles as $key => $role)
                                                    {{ $role->name}}<br>
                                                @endforeach
                                            @else

                                            @endif
                                        </td>
                                        <td>{{$user->created_at}}</td>
                                        <td>{{optional($user->creator)->name}}</td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
				</div>
				<div class="d-flex justify-content-center">

					{{$users->links()}}
				</div>
			</div>

			<input id="data-table-search" type="hidden" value="{{__('data_table.search')}}">
			<input id="data-table-zero-record" type="hidden" value="{{__('data_table.zeroRecords')}}">


@endsection

@section('head')
	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css"> -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
@endsection
@section('js_footer')
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function () {
			dataTable = $('#users').DataTable({
				"paging":   false,
				"info":     false,
				"language": {
					"search": $("#data-table-search").val(),
					"zeroRecords": $("#data-table-zero-record").val(),
				},
			});
			searchingOnUsersAjax();
		});
	</script>
@endsection

resources/views/users/index_users_not_verified_email.blade.php
@extends('layouts.app')
@section('title')
    المستخدمين الذين لم التحقق من البريد الإلكتروني الخاص بهم
@endsection
@section('content')
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				المستخدمين الذين لم التحقق من البريد الإلكتروني الخاص بهم
			</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover" id="owners">
							<thead>
								<tr>
									<th class="border-0">#</th>
									<th class="border-0">الاسم</th>
									<th class="border-0">البريد الإلكتروني</th>
									<th class="border-0">رقم المحمول </th>
									<th class="border-0">البلد </th>
									<th class="border-0">تاريخ تاريخ الاشتراك </th>
									<th class="border-0">نوع الاشتراك </th>
									<th class="border-0">تفعيل الاشتراك </th>
								</tr>
							</thead>
							<tbody>
								@foreach($usersNotVerified as $userKey => $user)
									<tr>
										<td>{{$userKey+1}}</td>
										<td>
                                            {{$user->name}}
										</td>
										<td>{{$user->email}}</td>
										<td>{{$user->mobile_number}}</td>
										<td>{{$user->country}}</td>
										<td>{{$user->created_at}}</td>
										<td>{{$user->type}}</td>
										<td>
                                            <a href="{{action('UserController@verifyUserEmail', ['user'=>$user->id])}}" role="button" class="btn btn-primary btn-sm">تفعيل</a>
                                        </td>
									</tr>
								@endforeach
							</tbody>
						</table>
					</div>

				</div>
				<div class="d-flex justify-content-center">
					{{$usersNotVerified->links()}}
				</div>
			</div>
	</div>
@endsection

@section('head')
	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css"> -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
@endsection
@section('js_footer')
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function () {
			dataTable = $('#owners').DataTable({
				"paging":   false,
				"info":     false,
				"language": {
					"search": "البحث في النتائج المعروضه: ",
					 "zeroRecords": "لا يوجد بيانات متاحة في الجدول",
				},
			});
		});
	</script>
@endsection